# Generated by Django 4.2.4 on 2025-07-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_extension_data_web_search_search_querry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extension_Data_BNS',
        ),
        migrations.DeleteModel(
            name='Extension_Data_BSA',
        ),
        migrations.DeleteModel(
            name='Extension_Data_IT',
        ),
        migrations.DeleteModel(
            name='Extension_Data_Web_Search',
        ),
    ]
